app = "vendre-auto"
primary_region = "cdg"

[build]

[env]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[build.args]
  VITE_SUPABASE_URL = "https://oancxlxjdstcahbfcqhx.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9hbmN4bHhqZHN0Y2FoYmZjcWh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEyODgxOTksImV4cCI6MjA4Njg2NDE5OX0.ETf6Bsm9ki5D5OLMiCkgI5FD0tDP96HrfL9JI7-rbWg"

[checks]
  [checks.http]
    port = 8080
    type = "http"
    interval = "15s"
    timeout = "10s"
    grace_period = "20s"
